id: P006885
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-17 12:28:39.875041
source_metadata:
  id: bdr:W2PD19887
  title: སློབ་གྲོགས།
  author: ''
  volumes:
    cde1eb5bd0ce403da6473af3cd9adb56:
      image_group_id: I2PD20549
      title: ''
      volume_number: 1
      total_pages: 86
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
