id: P006885
initial_creation_type: ocr
source_metadata:
  id: bdr:W2PD19887
  title: སློབ་གྲོགས།
  author: ''
  volumes:
    cde1eb5bd0ce403da6473af3cd9adb56:
      image_group_id: I2PD20549
      title: ''
      volume_number: 1
      total_pages: 86
      base_file: v001.txt
