id: I5553BB13
legacy_id: P006885
ocr_import_info:
  bdrc_scan_id: W2PD19887
  source: bdrc
  ocr_info:
    timestamp: '2020-03-27T08:48:05'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-27T11:18:10.667534+00:00'
last_modified: 2022-08-27 19:18:18.528138
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W2PD19887
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW2PD19887
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སློབ་གྲོགས།
statistics:
  ocr_word_mean_confidence_index: 0.8927495611222285
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I2PD20549:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD20549
      total_pages: 86
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I2PD20549.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.8927495611222285
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
